// SPDX-FileCopyrightText: 2026 Veydan Project
// SPDX-License-Identifier: LicenseRef-PolyForm-Perimeter-1.0.1

//! Bilingual demo catalog (EN / RU) of notes. Same entity ids; locale picks
//! labels and note bodies.

#[derive(Clone)]
pub struct NotesPack {
    pub folders: Vec<DemoFolder>,
    pub tags: Vec<DemoTag>,
    pub notes: Vec<DemoNote>,
    pub smart_views: Vec<DemoSmartView>,
}

#[derive(Clone)]
pub struct DemoFolder {
    pub id: &'static str,
    pub name: &'static str,
    pub parent_id: Option<&'static str>,
    pub color: &'static str,
}

#[derive(Clone)]
pub struct DemoTag {
    pub id: &'static str,
    pub name: &'static str,
    pub color: &'static str,
}

#[derive(Clone)]
pub struct DemoNote {
    pub title: &'static str,
    pub content: &'static str,
    pub tags: &'static [&'static str],
    pub folder_id: Option<&'static str>,
    pub bindings: &'static [&'static str],
    pub pinned: bool,
    pub archived: bool,
    pub deleted: bool,
}

#[derive(Clone, Copy)]
pub enum SmartKind {
    OpenTasks,
    Pinned,
    Recent7d,
    HasAttachments,
}

#[derive(Clone)]
pub struct DemoSmartView {
    pub name: &'static str,
    pub color: &'static str,
    pub kind: SmartKind,
}

fn t(ru: bool, en: &'static str, ru_s: &'static str) -> &'static str {
    if ru {
        ru_s
    } else {
        en
    }
}

/// Build the demo pack for `ru` or `en` (anything else → en).
pub fn pack(locale: &str) -> NotesPack {
    let ru = locale.eq_ignore_ascii_case("ru");
    NotesPack {
        folders: folders(ru),
        tags: tags(),
        notes: notes(ru),
        smart_views: smart_views(ru),
    }
}

fn folders(ru: bool) -> Vec<DemoFolder> {
    vec![
        DemoFolder {
            id: "demo-folder-templates",
            name: "Templates",
            parent_id: None,
            color: "#8b7bff",
        },
        DemoFolder {
            id: "demo-folder-smm",
            name: "SMM",
            parent_id: None,
            color: "#ec4899",
        },
        DemoFolder {
            id: "demo-folder-smm-content",
            name: t(ru, "Content", "Контент"),
            parent_id: Some("demo-folder-smm"),
            color: "#f9a8d4",
        },
        DemoFolder {
            id: "demo-folder-smm-clients",
            name: t(ru, "Clients", "Клиенты"),
            parent_id: Some("demo-folder-smm"),
            color: "#db2777",
        },
        DemoFolder {
            id: "demo-folder-dev",
            name: t(ru, "Development", "Разработка"),
            parent_id: None,
            color: "#3b82f6",
        },
        DemoFolder {
            id: "demo-folder-dev-arch",
            name: t(ru, "Architecture", "Архитектура"),
            parent_id: Some("demo-folder-dev"),
            color: "#60a5fa",
        },
        DemoFolder {
            id: "demo-folder-dev-snip",
            name: t(ru, "Snippets", "Сниппеты"),
            parent_id: Some("demo-folder-dev"),
            color: "#93c5fd",
        },
        DemoFolder {
            id: "demo-folder-devops",
            name: "DevOps",
            parent_id: None,
            color: "#10b981",
        },
        DemoFolder {
            id: "demo-folder-devops-run",
            name: "Runbooks",
            parent_id: Some("demo-folder-devops"),
            color: "#34d399",
        },
        DemoFolder {
            id: "demo-folder-devops-check",
            name: t(ru, "Checklists", "Чеклисты"),
            parent_id: Some("demo-folder-devops"),
            color: "#6ee7b7",
        },
        DemoFolder {
            id: "demo-folder-biz",
            name: t(ru, "Business", "Бизнес"),
            parent_id: None,
            color: "#f59e0b",
        },
        DemoFolder {
            id: "demo-folder-biz-meet",
            name: t(ru, "Meetings", "Встречи"),
            parent_id: Some("demo-folder-biz"),
            color: "#fbbf24",
        },
        DemoFolder {
            id: "demo-folder-biz-fin",
            name: t(ru, "Finance", "Финансы"),
            parent_id: Some("demo-folder-biz"),
            color: "#fcd34d",
        },
        DemoFolder {
            id: "demo-folder-personal",
            name: t(ru, "Personal", "Личное"),
            parent_id: None,
            color: "#6b7280",
        },
        DemoFolder {
            id: "demo-folder-inbox",
            name: "Inbox",
            parent_id: None,
            color: "#94a3b8",
        },
    ]
}

fn tags() -> Vec<DemoTag> {
    vec![
        DemoTag {
            id: "demo-tag-smm",
            name: "work/smm",
            color: "#ec4899",
        },
        DemoTag {
            id: "demo-tag-dev",
            name: "work/dev",
            color: "#3b82f6",
        },
        DemoTag {
            id: "demo-tag-devops",
            name: "work/devops",
            color: "#10b981",
        },
        DemoTag {
            id: "demo-tag-biz",
            name: "work/biz",
            color: "#f59e0b",
        },
        DemoTag {
            id: "demo-tag-personal",
            name: "personal",
            color: "#6b7280",
        },
        DemoTag {
            id: "demo-tag-todo",
            name: "status/todo",
            color: "#94a3b8",
        },
        DemoTag {
            id: "demo-tag-wip",
            name: "status/wip",
            color: "#3b82f6",
        },
        DemoTag {
            id: "demo-tag-done",
            name: "status/done",
            color: "#22c55e",
        },
        DemoTag {
            id: "demo-tag-brand",
            name: "client/brand-a",
            color: "#db2777",
        },
        DemoTag {
            id: "demo-tag-prod",
            name: "infra/prod",
            color: "#ef4444",
        },
        DemoTag {
            id: "demo-tag-staging",
            name: "infra/staging",
            color: "#f59e0b",
        },
    ]
}

fn smart_views(ru: bool) -> Vec<DemoSmartView> {
    vec![
        DemoSmartView {
            name: t(ru, "Open tasks", "Открытые задачи"),
            color: "#f59e0b",
            kind: SmartKind::OpenTasks,
        },
        DemoSmartView {
            name: t(ru, "Pinned", "Закреплённые"),
            color: "#8b7bff",
            kind: SmartKind::Pinned,
        },
        DemoSmartView {
            name: t(ru, "Recent 7 days", "За 7 дней"),
            color: "#3b82f6",
            kind: SmartKind::Recent7d,
        },
        DemoSmartView {
            name: t(ru, "With attachments", "С вложениями"),
            color: "#10b981",
            kind: SmartKind::HasAttachments,
        },
    ]
}

fn notes(ru: bool) -> Vec<DemoNote> {
    if ru {
        notes_ru()
    } else {
        notes_en()
    }
}

fn notes_en() -> Vec<DemoNote> {
    vec![
        // Templates first
        DemoNote {
            title: "Meeting template",
            content: "# {{title}}\n\n**Date:** {{date}}\n\n## Attendees\n- \n\n## Agenda\n1. \n\n## Notes\n\n## Action items\n- [ ] \n",
            tags: &[],
            folder_id: Some("demo-folder-templates"),
            bindings: &[],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Incident template",
            content: "# Incident: {{title}}\n\n**Started:** {{date}}\n**Severity:** SEV-?\n\n## Impact\n\n## Timeline\n\n## Root cause\n\n## Follow-ups\n- [ ] \n",
            tags: &["work/devops"],
            folder_id: Some("demo-folder-templates"),
            bindings: &[],
            pinned: false,
            archived: false,
            deleted: false,
        },
        // SMM (7)
        DemoNote {
            title: "Content plan week",
            content: "# Content plan — week\n\n| Day | Channel | Topic |\n|-----|---------|-------|\n| Mon | IG | Product teaser |\n| Wed | TikTok | Behind the scenes |\n| Fri | LinkedIn | Case study |\n\nSee also [[Hashtag set Brand A]].\n\n- [x] Draft IG carousel\n- [ ] Film TikTok\n- [ ] Schedule LinkedIn\n",
            tags: &["work/smm", "status/wip", "client/brand-a"],
            folder_id: Some("demo-folder-smm-content"),
            bindings: &["workspace:demo-ws-smm", "profile:demo-pr-ig"],
            pinned: true,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Hashtag set Brand A",
            content: "# Hashtags — Brand A\n\nPrimary:\n`#BrandA #NewDrop #MadeForYou`\n\nSecondary:\n`#Lifestyle #DailyInspo #Creators`\n\nAvoid overused tags. Max 12 per post.\n",
            tags: &["work/smm", "client/brand-a"],
            folder_id: Some("demo-folder-smm-content"),
            bindings: &["workspace:demo-ws-smm"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Client brief Brand A",
            content: "# Brief — Brand A Q2\n\n**Goal:** +20% engagement\n**Tone:** warm, practical\n**Must show:** product in real use\n\nDeliverables:\n- 12 Reels\n- 8 carousels\n- 4 LinkedIn posts\n",
            tags: &["work/smm", "client/brand-a"],
            folder_id: Some("demo-folder-smm-clients"),
            bindings: &["workspace:demo-ws-smm", "domain:instagram.com"],
            pinned: true,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Reels calendar",
            content: "# Reels calendar\n\n- [ ] Hook tests (3 variants)\n- [ ] Captions in EN + RU\n- [x] Thumbnails batch\n\nProfile: Instagram Brand A.\n",
            tags: &["work/smm", "status/todo"],
            folder_id: Some("demo-folder-smm-content"),
            bindings: &["profile:demo-pr-ig"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Competitors watch",
            content: "# Competitors\n\n1. RivalCo — strong Reels cadence\n2. AltBrand — better UGC\n3. NicheLab — weak CTAs\n\nSteal with pride: end-card format from RivalCo.\n",
            tags: &["work/smm"],
            folder_id: Some("demo-folder-smm-clients"),
            bindings: &["workspace:demo-ws-smm"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "UTM scheme",
            content: "# UTM scheme\n\n```\nutm_source=instagram|tiktok|linkedin\nutm_medium=social\nutm_campaign=brand_a_q2\nutm_content={{post_id}}\n```\n\nStore in sheet before publish.\n",
            tags: &["work/smm", "status/done"],
            folder_id: Some("demo-folder-smm-content"),
            bindings: &["workspace:demo-ws-smm"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Post draft IG",
            content: "# Draft — IG carousel\n\nSlide 1: Problem\nSlide 2: Insight\nSlide 3: Product\nSlide 4: CTA\n\nCaption draft links to [[Content plan week]].\n\n- [ ] Design pass\n- [ ] Legal check\n",
            tags: &["work/smm", "status/wip", "client/brand-a"],
            folder_id: Some("demo-folder-smm-content"),
            bindings: &["profile:demo-pr-ig", "domain:instagram.com"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        // Dev (7)
        DemoNote {
            title: "ADR auth",
            content: "# ADR: Session auth\n\n## Context\nNeed shared login across desktop and mobile.\n\n## Decision\nCookie + device-bound refresh token.\n\n## Consequences\n- Simpler SSO\n- Must rotate refresh on logout\n\nRelated: [[API contracts]].\n",
            tags: &["work/dev", "status/done"],
            folder_id: Some("demo-folder-dev-arch"),
            bindings: &["workspace:demo-ws-dev"],
            pinned: true,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "API contracts",
            content: "# API contracts\n\n`POST /v1/sessions` — create\n`GET /v1/me` — current user\n`DELETE /v1/sessions/:id` — logout\n\nErrors: `401`, `409`, `429`.\n\nImplements [[ADR auth]].\n",
            tags: &["work/dev"],
            folder_id: Some("demo-folder-dev-arch"),
            bindings: &["workspace:demo-ws-dev", "profile:demo-pr-gh", "domain:github.com"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "SQL migrate snippet",
            content: "# SQL migrate\n\n```sql\nALTER TABLE accounts ADD COLUMN locale TEXT NOT NULL DEFAULT 'en';\nCREATE INDEX idx_accounts_locale ON accounts(locale);\n```\n\nRun on staging first.\n",
            tags: &["work/dev", "infra/staging"],
            folder_id: Some("demo-folder-dev-snip"),
            bindings: &["workspace:demo-ws-dev"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Sprint TODO",
            content: "# Sprint TODO\n\n- [x] Auth ADR merged\n- [ ] Rate limit middleware\n- [ ] Mobile offline queue\n- [ ] E2E smoke for notes\n\nOwner: platform team.\n",
            tags: &["work/dev", "status/todo"],
            folder_id: Some("demo-folder-dev"),
            bindings: &["workspace:demo-ws-dev", "profile:demo-pr-gh"],
            pinned: true,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Changelog draft",
            content: "# Changelog\n\n## Unreleased\n- Demo data loader\n- Notes smart views\n\n## 0.9.0\n- SSH key store\n- TOTP vault\n",
            tags: &["work/dev"],
            folder_id: Some("demo-folder-dev"),
            bindings: &["workspace:demo-ws-dev"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Repo onboarding",
            content: "# Onboarding\n\n1. Install Rust + Node\n2. `pnpm install`\n3. `make dev`\n\nDocs live under `/docs`. Ask in #eng.\n",
            tags: &["work/dev", "status/done"],
            folder_id: Some("demo-folder-dev"),
            bindings: &["domain:github.com"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Old spike notes",
            content: "# Spike (archived)\n\nTried embedding SQLite in WASM — dropped for size.\n",
            tags: &["work/dev"],
            folder_id: Some("demo-folder-dev"),
            bindings: &["workspace:demo-ws-dev"],
            pinned: false,
            archived: true,
            deleted: false,
        },
        // DevOps (7)
        DemoNote {
            title: "Deploy runbook",
            content: "# Deploy runbook\n\n1. Freeze deploys in Slack\n2. `ssh prod-web-01`\n3. Pull tag, migrate, restart\n4. Check Grafana\n\nRollback: [[Rollback checklist]].\n",
            tags: &["work/devops", "infra/prod", "status/wip"],
            folder_id: Some("demo-folder-devops-run"),
            bindings: &["workspace:demo-ws-devops", "profile:demo-pr-aws"],
            pinned: true,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Rollback checklist",
            content: "# Rollback checklist\n\n| Step | Owner | Done |\n|------|-------|------|\n| Revert image | on-call | [ ] |\n| Restore DB snapshot | DBA | [ ] |\n| Verify health | on-call | [ ] |\n| Unfreeze | lead | [ ] |\n",
            tags: &["work/devops", "infra/prod"],
            folder_id: Some("demo-folder-devops-check"),
            bindings: &["workspace:demo-ws-devops"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Nginx snippet",
            content: "# Nginx snippet\n\n```nginx\nlocation /api/ {\n  proxy_pass http://127.0.0.1:8080;\n  proxy_set_header X-Request-Id $request_id;\n}\n```\n",
            tags: &["work/devops"],
            folder_id: Some("demo-folder-devops-run"),
            bindings: &["workspace:demo-ws-devops"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Monitoring alerts",
            content: "# Alerts\n\n- `http_5xx > 2%` for 5m → PagerDuty\n- `disk > 85%` → Slack #infra\n- `cert_expiry < 14d` → email\n\nDashboard: Grafana profile.\n",
            tags: &["work/devops", "status/todo"],
            folder_id: Some("demo-folder-devops-run"),
            bindings: &["profile:demo-pr-grafana"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Capacity notes",
            content: "# Capacity\n\nProd: 3× c6i.large, avg CPU 35%.\nNeed +1 node before Black Friday.\n\n- [ ] Order instance\n- [ ] Update ASG\n",
            tags: &["work/devops", "infra/prod"],
            folder_id: Some("demo-folder-devops"),
            bindings: &["workspace:demo-ws-devops"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "SSH inventory",
            content: "# SSH inventory\n\n- `prod-web-01` — key + 2FA\n- `staging-api` — password\n- `bastion` — jump\n- `ci-runner` — deploy key\n\nPasswords are placeholders for the demo.\n",
            tags: &["work/devops"],
            folder_id: Some("demo-folder-devops"),
            bindings: &["workspace:demo-ws-devops"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Incident postmortem",
            content: "# Postmortem — cache stampede\n\n**Impact:** 12m elevated latency\n**Root cause:** missing lock on warm cache\n**Fix:** singleflight + jitter\n\nFollow-ups tracked in sprint.\n",
            tags: &["work/devops", "status/done"],
            folder_id: Some("demo-folder-devops"),
            bindings: &["workspace:demo-ws-devops"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        // Biz (6)
        DemoNote {
            title: "Deal pipeline",
            content: "# Pipeline\n\n| Deal | Stage | ARR |\n|------|-------|-----|\n| Northwind | Negotiation | $48k |\n| Contoso | Lead | $12k |\n| Fabrikam | Closed | $90k |\n",
            tags: &["work/biz", "status/wip"],
            folder_id: Some("demo-folder-biz"),
            bindings: &["workspace:demo-ws-biz", "profile:demo-pr-crm"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Investor meeting",
            content: "# Investor meeting\n\n**Ask:** seed extension\n**Deck:** pitch one-pager\n\nNotes:\n- Liked retention chart\n- Want clearer CAC\n\n- [ ] Update financials\n- [ ] Send follow-up\n",
            tags: &["work/biz", "status/todo"],
            folder_id: Some("demo-folder-biz-meet"),
            bindings: &["workspace:demo-ws-biz"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "P and L draft",
            content: "# P&L draft (month)\n\n| Item | Amount |\n|------|--------|\n| Revenue | 42,000 |\n| COGS | 8,500 |\n| OpEx | 21,000 |\n| Net | 12,500 |\n",
            tags: &["work/biz"],
            folder_id: Some("demo-folder-biz-fin"),
            bindings: &["workspace:demo-ws-biz"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Partner contacts",
            content: "# Partners\n\n- **Ada** — agency lead — ada@example.com\n- **Ben** — reseller — ben@example.com\n- **Cara** — legal — cara@example.com\n",
            tags: &["work/biz"],
            folder_id: Some("demo-folder-biz"),
            bindings: &["workspace:demo-ws-biz"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Contract checklist",
            content: "# Contract checklist\n\n- [x] NDA signed\n- [ ] MSA reviewed\n- [ ] DPA attached\n- [ ] Invoice schedule\n",
            tags: &["work/biz", "status/todo"],
            folder_id: Some("demo-folder-biz"),
            bindings: &["workspace:demo-ws-biz"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Pitch one-pager",
            content: "# Pitch one-pager\n\n**Problem:** multi-account chaos\n**Product:** profiles + notes + TOTP + SSH in one vault\n**Moat:** local-first sync\n",
            tags: &["work/biz", "status/done"],
            folder_id: Some("demo-folder-biz-meet"),
            bindings: &["workspace:demo-ws-biz"],
            pinned: false,
            archived: true,
            deleted: false,
        },
        // Personal (5)
        DemoNote {
            title: "Monthly budget",
            content: "# Budget\n\n| Category | Plan |\n|----------|------|\n| Rent | 1200 |\n| Food | 400 |\n| Tools | 80 |\n| Fun | 150 |\n",
            tags: &["personal"],
            folder_id: Some("demo-folder-personal"),
            bindings: &["workspace:default"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Travel wishlist",
            content: "# Travel wishlist\n\n- Lisbon in spring\n- Tokyo for cherry blossoms\n- Road trip Alps\n\n- [ ] Check flight deals\n",
            tags: &["personal", "status/todo"],
            folder_id: Some("demo-folder-personal"),
            bindings: &["workspace:default"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Health log",
            content: "# Health log\n\nSleep avg 7h. Gym 3×/week.\n\nNext checkup: dentist.\n",
            tags: &["personal"],
            folder_id: Some("demo-folder-personal"),
            bindings: &["workspace:default", "profile:demo-pr-bank"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "WiFi codes home",
            content: "# Home Wi‑Fi\n\nSSID: `HomeLab`\nPass: `demo-wifi-not-real`\n\nGuest VLAN: `HomeGuest`.\n\nNotes lock and password vault: `demo`.\n",
            tags: &["personal"],
            folder_id: Some("demo-folder-personal"),
            bindings: &["workspace:default"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Reading list",
            content: "# Reading list\n\n- Designing Data-Intensive Applications\n- Staff Engineer\n- The Mom Test\n",
            tags: &["personal", "status/wip"],
            folder_id: Some("demo-folder-personal"),
            bindings: &[],
            pinned: false,
            archived: false,
            deleted: false,
        },
        // Inbox (2)
        DemoNote {
            title: "Quick capture",
            content: "# Quick capture\n\nIdea: show TOTP badge on kanban cards — already shipped, verify on mobile.\n",
            tags: &["status/todo"],
            folder_id: Some("demo-folder-inbox"),
            bindings: &[],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Feature idea vault search",
            content: "# Idea: vault-wide search\n\nSearch notes + TOTP names + SSH hosts in one box.\n\nTrash this if duplicated.\n",
            tags: &[],
            folder_id: Some("demo-folder-inbox"),
            bindings: &[],
            pinned: false,
            archived: false,
            deleted: true,
        },
    ]
}

fn notes_ru() -> Vec<DemoNote> {
    vec![
        DemoNote {
            title: "Шаблон встречи",
            content: "# {{title}}\n\n**Дата:** {{date}}\n\n## Участники\n- \n\n## Повестка\n1. \n\n## Заметки\n\n## Действия\n- [ ] \n",
            tags: &[],
            folder_id: Some("demo-folder-templates"),
            bindings: &[],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Шаблон инцидента",
            content: "# Инцидент: {{title}}\n\n**Начало:** {{date}}\n**Severity:** SEV-?\n\n## Влияние\n\n## Таймлайн\n\n## Причина\n\n## Follow-up\n- [ ] \n",
            tags: &["work/devops"],
            folder_id: Some("demo-folder-templates"),
            bindings: &[],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Контент-план недели",
            content: "# Контент-план — неделя\n\n| День | Канал | Тема |\n|------|-------|------|\n| Пн | IG | Тизер продукта |\n| Ср | TikTok | Закулисье |\n| Пт | LinkedIn | Кейс |\n\nСм. [[Набор хештегов Brand A]].\n\n- [x] Черновик карусели IG\n- [ ] Снять TikTok\n- [ ] Запланировать LinkedIn\n",
            tags: &["work/smm", "status/wip", "client/brand-a"],
            folder_id: Some("demo-folder-smm-content"),
            bindings: &["workspace:demo-ws-smm", "profile:demo-pr-ig"],
            pinned: true,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Набор хештегов Brand A",
            content: "# Хештеги — Brand A\n\nОсновные:\n`#BrandA #NewDrop #MadeForYou`\n\nДоп.:\n`#Lifestyle #DailyInspo #Creators`\n\nНе больше 12 на пост.\n",
            tags: &["work/smm", "client/brand-a"],
            folder_id: Some("demo-folder-smm-content"),
            bindings: &["workspace:demo-ws-smm"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Бриф клиента Brand A",
            content: "# Бриф — Brand A Q2\n\n**Цель:** +20% engagement\n**Тон:** тёплый, практичный\n**Показывать:** продукт в жизни\n\nDeliverables:\n- 12 Reels\n- 8 каруселей\n- 4 поста LinkedIn\n",
            tags: &["work/smm", "client/brand-a"],
            folder_id: Some("demo-folder-smm-clients"),
            bindings: &["workspace:demo-ws-smm", "domain:instagram.com"],
            pinned: true,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Календарь Reels",
            content: "# Календарь Reels\n\n- [ ] Тесты хуков (3 варианта)\n- [ ] Подписи EN + RU\n- [x] Пакет обложек\n\nПрофиль: Instagram Brand A.\n",
            tags: &["work/smm", "status/todo"],
            folder_id: Some("demo-folder-smm-content"),
            bindings: &["profile:demo-pr-ig"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Конкуренты",
            content: "# Конкуренты\n\n1. RivalCo — сильные Reels\n2. AltBrand — лучше UGC\n3. NicheLab — слабые CTA\n\nВзять формат end-card у RivalCo.\n",
            tags: &["work/smm"],
            folder_id: Some("demo-folder-smm-clients"),
            bindings: &["workspace:demo-ws-smm"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Схема UTM",
            content: "# Схема UTM\n\n```\nutm_source=instagram|tiktok|linkedin\nutm_medium=social\nutm_campaign=brand_a_q2\nutm_content={{post_id}}\n```\n\nФиксировать в таблице до публикации.\n",
            tags: &["work/smm", "status/done"],
            folder_id: Some("demo-folder-smm-content"),
            bindings: &["workspace:demo-ws-smm"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Черновик поста IG",
            content: "# Черновик — карусель IG\n\nСлайд 1: Проблема\nСлайд 2: Инсайт\nСлайд 3: Продукт\nСлайд 4: CTA\n\nПодпись → [[Контент-план недели]].\n\n- [ ] Дизайн\n- [ ] Юр. проверка\n",
            tags: &["work/smm", "status/wip", "client/brand-a"],
            folder_id: Some("demo-folder-smm-content"),
            bindings: &["profile:demo-pr-ig", "domain:instagram.com"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "ADR auth",
            content: "# ADR: сессионная auth\n\n## Контекст\nНужен общий логин desktop + mobile.\n\n## Решение\nCookie + refresh, привязанный к устройству.\n\n## Последствия\n- Проще SSO\n- Ротация refresh при logout\n\nСвязано: [[API contracts]].\n",
            tags: &["work/dev", "status/done"],
            folder_id: Some("demo-folder-dev-arch"),
            bindings: &["workspace:demo-ws-dev"],
            pinned: true,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "API contracts",
            content: "# API contracts\n\n`POST /v1/sessions` — создать\n`GET /v1/me` — текущий пользователь\n`DELETE /v1/sessions/:id` — выход\n\nОшибки: `401`, `409`, `429`.\n\nРеализует [[ADR auth]].\n",
            tags: &["work/dev"],
            folder_id: Some("demo-folder-dev-arch"),
            bindings: &["workspace:demo-ws-dev", "profile:demo-pr-gh", "domain:github.com"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "SQL migrate snippet",
            content: "# SQL migrate\n\n```sql\nALTER TABLE accounts ADD COLUMN locale TEXT NOT NULL DEFAULT 'en';\nCREATE INDEX idx_accounts_locale ON accounts(locale);\n```\n\nСначала на staging.\n",
            tags: &["work/dev", "infra/staging"],
            folder_id: Some("demo-folder-dev-snip"),
            bindings: &["workspace:demo-ws-dev"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Sprint TODO",
            content: "# Sprint TODO\n\n- [x] Auth ADR смержен\n- [ ] Rate limit middleware\n- [ ] Offline queue на mobile\n- [ ] E2E smoke для notes\n\nВладелец: platform.\n",
            tags: &["work/dev", "status/todo"],
            folder_id: Some("demo-folder-dev"),
            bindings: &["workspace:demo-ws-dev", "profile:demo-pr-gh"],
            pinned: true,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Changelog draft",
            content: "# Changelog\n\n## Unreleased\n- Загрузчик демо-данных\n- Smart views для заметок\n\n## 0.9.0\n- Хранилище SSH-ключей\n- TOTP vault\n",
            tags: &["work/dev"],
            folder_id: Some("demo-folder-dev"),
            bindings: &["workspace:demo-ws-dev"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Онбординг репо",
            content: "# Онбординг\n\n1. Установить Rust + Node\n2. `pnpm install`\n3. `make dev`\n\nДоки в `/docs`. Вопросы в #eng.\n",
            tags: &["work/dev", "status/done"],
            folder_id: Some("demo-folder-dev"),
            bindings: &["domain:github.com"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Старый спайк",
            content: "# Спайк (архив)\n\nПробовали SQLite в WASM — отказались из‑за размера.\n",
            tags: &["work/dev"],
            folder_id: Some("demo-folder-dev"),
            bindings: &["workspace:demo-ws-dev"],
            pinned: false,
            archived: true,
            deleted: false,
        },
        DemoNote {
            title: "Runbook деплоя",
            content: "# Runbook деплоя\n\n1. Freeze в Slack\n2. `ssh prod-web-01`\n3. Pull tag, migrate, restart\n4. Проверить Grafana\n\nОткат: [[Чеклист отката]].\n",
            tags: &["work/devops", "infra/prod", "status/wip"],
            folder_id: Some("demo-folder-devops-run"),
            bindings: &["workspace:demo-ws-devops", "profile:demo-pr-aws"],
            pinned: true,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Чеклист отката",
            content: "# Чеклист отката\n\n| Шаг | Владелец | Done |\n|-----|----------|------|\n| Откатить image | on-call | [ ] |\n| Снапшот БД | DBA | [ ] |\n| Health-check | on-call | [ ] |\n| Unfreeze | lead | [ ] |\n",
            tags: &["work/devops", "infra/prod"],
            folder_id: Some("demo-folder-devops-check"),
            bindings: &["workspace:demo-ws-devops"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Nginx snippet",
            content: "# Nginx snippet\n\n```nginx\nlocation /api/ {\n  proxy_pass http://127.0.0.1:8080;\n  proxy_set_header X-Request-Id $request_id;\n}\n```\n",
            tags: &["work/devops"],
            folder_id: Some("demo-folder-devops-run"),
            bindings: &["workspace:demo-ws-devops"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Алерты мониторинга",
            content: "# Алерты\n\n- `http_5xx > 2%` 5m → PagerDuty\n- `disk > 85%` → Slack #infra\n- `cert_expiry < 14d` → email\n\nДашборд: профиль Grafana.\n",
            tags: &["work/devops", "status/todo"],
            folder_id: Some("demo-folder-devops-run"),
            bindings: &["profile:demo-pr-grafana"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Заметки по ёмкости",
            content: "# Ёмкость\n\nProd: 3× c6i.large, CPU ~35%.\nНужен +1 узел до Чёрной пятницы.\n\n- [ ] Заказать инстанс\n- [ ] Обновить ASG\n",
            tags: &["work/devops", "infra/prod"],
            folder_id: Some("demo-folder-devops"),
            bindings: &["workspace:demo-ws-devops"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "SSH inventory",
            content: "# SSH inventory\n\n- `prod-web-01` — ключ + 2FA\n- `staging-api` — пароль\n- `bastion` — jump\n- `ci-runner` — deploy key\n\nПароли — плейсхолдеры для демо.\n",
            tags: &["work/devops"],
            folder_id: Some("demo-folder-devops"),
            bindings: &["workspace:demo-ws-devops"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Постмортем инцидента",
            content: "# Постмортем — cache stampede\n\n**Влияние:** 12 мин latency\n**Причина:** нет lock на прогреве кэша\n**Фикс:** singleflight + jitter\n\nFollow-up в спринте.\n",
            tags: &["work/devops", "status/done"],
            folder_id: Some("demo-folder-devops"),
            bindings: &["workspace:demo-ws-devops"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Воронка сделок",
            content: "# Воронка\n\n| Сделка | Этап | ARR |\n|--------|------|-----|\n| Northwind | Переговоры | $48k |\n| Contoso | Lead | $12k |\n| Fabrikam | Closed | $90k |\n",
            tags: &["work/biz", "status/wip"],
            folder_id: Some("demo-folder-biz"),
            bindings: &["workspace:demo-ws-biz", "profile:demo-pr-crm"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Встреча с инвестором",
            content: "# Встреча с инвестором\n\n**Ask:** seed extension\n**Deck:** pitch one-pager\n\nЗаметки:\n- Понравился retention\n- Просят яснее CAC\n\n- [ ] Обновить финансы\n- [ ] Follow-up письмо\n",
            tags: &["work/biz", "status/todo"],
            folder_id: Some("demo-folder-biz-meet"),
            bindings: &["workspace:demo-ws-biz"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Черновик P and L",
            content: "# Черновик P&L (месяц)\n\n| Статья | Сумма |\n|--------|-------|\n| Выручка | 42,000 |\n| COGS | 8,500 |\n| OpEx | 21,000 |\n| Net | 12,500 |\n",
            tags: &["work/biz"],
            folder_id: Some("demo-folder-biz-fin"),
            bindings: &["workspace:demo-ws-biz"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Контакты партнёров",
            content: "# Партнёры\n\n- **Ada** — agency — ada@example.com\n- **Ben** — reseller — ben@example.com\n- **Cara** — legal — cara@example.com\n",
            tags: &["work/biz"],
            folder_id: Some("demo-folder-biz"),
            bindings: &["workspace:demo-ws-biz"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Чеклист договора",
            content: "# Чеклист договора\n\n- [x] NDA подписан\n- [ ] MSA на ревью\n- [ ] DPA приложен\n- [ ] График счетов\n",
            tags: &["work/biz", "status/todo"],
            folder_id: Some("demo-folder-biz"),
            bindings: &["workspace:demo-ws-biz"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Pitch one-pager",
            content: "# Pitch one-pager\n\n**Проблема:** хаос мультиаккаунтов\n**Продукт:** профили + заметки + TOTP + SSH в одном vault\n**Moat:** local-first sync\n",
            tags: &["work/biz", "status/done"],
            folder_id: Some("demo-folder-biz-meet"),
            bindings: &["workspace:demo-ws-biz"],
            pinned: false,
            archived: true,
            deleted: false,
        },
        DemoNote {
            title: "Бюджет месяца",
            content: "# Бюджет\n\n| Категория | План |\n|-----------|------|\n| Аренда | 1200 |\n| Еда | 400 |\n| Инструменты | 80 |\n| Развлечения | 150 |\n",
            tags: &["personal"],
            folder_id: Some("demo-folder-personal"),
            bindings: &["workspace:default"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Wishlist путешествий",
            content: "# Wishlist путешествий\n\n- Лиссабон весной\n- Токио на сакуру\n- Роудтрип по Альпам\n\n- [ ] Смотреть авиабилеты\n",
            tags: &["personal", "status/todo"],
            folder_id: Some("demo-folder-personal"),
            bindings: &["workspace:default"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Health log",
            content: "# Health log\n\nСон ~7ч. Зал 3×/нед.\n\nСледующий чекап: стоматолог.\n",
            tags: &["personal"],
            folder_id: Some("demo-folder-personal"),
            bindings: &["workspace:default", "profile:demo-pr-bank"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "WiFi дома",
            content: "# Домашний Wi‑Fi\n\nSSID: `HomeLab`\nPass: `demo-wifi-not-real`\n\nGuest VLAN: `HomeGuest`.\n\nПароль блокировки и хранилища паролей: `demo`.\n",
            tags: &["personal"],
            folder_id: Some("demo-folder-personal"),
            bindings: &["workspace:default"],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Список чтения",
            content: "# Список чтения\n\n- Designing Data-Intensive Applications\n- Staff Engineer\n- The Mom Test\n",
            tags: &["personal", "status/wip"],
            folder_id: Some("demo-folder-personal"),
            bindings: &[],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Быстрый захват",
            content: "# Быстрый захват\n\nИдея: бейдж TOTP на kanban — уже есть, проверить на mobile.\n",
            tags: &["status/todo"],
            folder_id: Some("demo-folder-inbox"),
            bindings: &[],
            pinned: false,
            archived: false,
            deleted: false,
        },
        DemoNote {
            title: "Идея поиска по vault",
            content: "# Идея: поиск по vault\n\nИскать заметки + имена TOTP + SSH-хосты в одном поле.\n\nУдалить, если дубль.\n",
            tags: &[],
            folder_id: Some("demo-folder-inbox"),
            bindings: &[],
            pinned: false,
            archived: false,
            deleted: true,
        },
    ]
}
