// SPDX-FileCopyrightText: 2026 Veydan Project
// SPDX-License-Identifier: LicenseRef-PolyForm-Perimeter-1.0.1

//! Certificates made for the tests. They guard nothing: the keys are
//! right here. Kept as text in the source so that no rule about key
//! files in a repository hides them from a build.
//!
//! As a bridge has them since identity v2: a chain of two certificates,
//! the TLS one (over a P-256 key, the kind every browser takes) signed by
//! the bridge's own Ed25519 key, and the certificate carrying that key
//! behind it. The id is of the bridge's key. `CERT` over `KEY` and
//! `RENEWED_CERT` over `RENEWED_KEY` are two chains signed by one
//! bridge's key: one bridge, its TLS key replaced. `OTHER_CERT` over
//! `OTHER_KEY` is signed by another bridge's key. The same ones are in
//! `services/link/crates/vlink-proto/src/id.rs`; made with openssl.

pub const CERT: &str = "\
-----BEGIN CERTIFICATE-----\n\
MIIBcDCCASKgAwIBAgIIEgECAwQFBgcwBQYDK2VwMBQxEjAQBgNVBAMMCWxvY2Fs\n\
aG9zdDAeFw0yNjAxMDEwMDAwMDBaFw00NjAxMDEwMDAwMDBaMBQxEjAQBgNVBAMM\n\
CWxvY2FsaG9zdDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABBB5SEYuVXn0OBvk\n\
8JgDvZjmBXhKljRiizwcmR+FsaGmwQjSJVDL7hKFvLHiLCaJrtS0TLbJ8JMfRDmU\n\
BwRZ4mejYzBhMBQGA1UdEQQNMAuCCWxvY2FsaG9zdDAJBgNVHRMEAjAAMB0GA1Ud\n\
DgQWBBTi7QFLPRpIsYYCh2kTpKwGjEdqZDAfBgNVHSMEGDAWgBSSpKpC7ROmIhJk\n\
WUT70j9bznyGNjAFBgMrZXADQQAZqOG7Cb/n0YlTAjj/Sipf2vKRugebIQ3u5np6\n\
MItZBdiYrW1ssfR1Hy8f/jDlkAPDnr6i9cJvMMzayqz7H/gI\n\
-----END CERTIFICATE-----\n\
-----BEGIN CERTIFICATE-----\n\
MIIBQDCB86ADAgECAggRAQIDBAUGBzAFBgMrZXAwFDESMBAGA1UEAwwJbG9jYWxo\n\
b3N0MB4XDTI2MDEwMTAwMDAwMFoXDTQ2MDEwMTAwMDAwMFowFDESMBAGA1UEAwwJ\n\
bG9jYWxob3N0MCowBQYDK2VwAyEAma81HXyEZ69LHkAox9PHH4gHRfMzP5TPyELz\n\
NIf/CQajYzBhMB0GA1UdDgQWBBSSpKpC7ROmIhJkWUT70j9bznyGNjAfBgNVHSME\n\
GDAWgBSSpKpC7ROmIhJkWUT70j9bznyGNjAPBgNVHRMBAf8EBTADAQH/MA4GA1Ud\n\
DwEB/wQEAwIChDAFBgMrZXADQQDkQGhf0eDYbccl7Nj6TcPnQKmt6laKwFOr5yG0\n\
G6q2QCNmMRbfAqxRF2TSVhIVFzAW9Tc+QuZrqYqsTQdvUlgK\n\
-----END CERTIFICATE-----\n\
";

pub const KEY: &str = "\
-----BEGIN PRIVATE KEY-----\n\
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgkXe8oqgj8oAoJ5TF\n\
mXiQprL7fZBCBJe4duDTi5QlFuehRANCAAQQeUhGLlV59Dgb5PCYA72Y5gV4SpY0\n\
Yos8HJkfhbGhpsEI0iVQy+4Shbyx4iwmia7UtEy2yfCTH0Q5lAcEWeJn\n\
-----END PRIVATE KEY-----\n\
";

pub const RENEWED_CERT: &str = "\
-----BEGIN CERTIFICATE-----\n\
MIIBcDCCASKgAwIBAgIIIgECAwQFBgcwBQYDK2VwMBQxEjAQBgNVBAMMCWxvY2Fs\n\
aG9zdDAeFw0yNjAxMDEwMDAwMDBaFw00NjAxMDEwMDAwMDBaMBQxEjAQBgNVBAMM\n\
CWxvY2FsaG9zdDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABC5C0VXx8b5l0BF2\n\
ep+rvDQSS+lhHXzTu5yyyyJ9l4A9Q2ZVdZsLYj/YOusFtonsm2YgkTs3Sga8pgGI\n\
Napqv5ujYzBhMBQGA1UdEQQNMAuCCWxvY2FsaG9zdDAJBgNVHRMEAjAAMB0GA1Ud\n\
DgQWBBQ1nDJ46qVUSdFfVVhBLCSSDFdAbDAfBgNVHSMEGDAWgBSSpKpC7ROmIhJk\n\
WUT70j9bznyGNjAFBgMrZXADQQA+MnaUCTcBlxcAymzlQaQ/hWskXMM5FVx8/PSG\n\
mb+K8/qXV04P0q42IqDvdW33kKsvD/a9r8nVFtKCKEKolHIA\n\
-----END CERTIFICATE-----\n\
-----BEGIN CERTIFICATE-----\n\
MIIBQDCB86ADAgECAggRAQIDBAUGBzAFBgMrZXAwFDESMBAGA1UEAwwJbG9jYWxo\n\
b3N0MB4XDTI2MDEwMTAwMDAwMFoXDTQ2MDEwMTAwMDAwMFowFDESMBAGA1UEAwwJ\n\
bG9jYWxob3N0MCowBQYDK2VwAyEAma81HXyEZ69LHkAox9PHH4gHRfMzP5TPyELz\n\
NIf/CQajYzBhMB0GA1UdDgQWBBSSpKpC7ROmIhJkWUT70j9bznyGNjAfBgNVHSME\n\
GDAWgBSSpKpC7ROmIhJkWUT70j9bznyGNjAPBgNVHRMBAf8EBTADAQH/MA4GA1Ud\n\
DwEB/wQEAwIChDAFBgMrZXADQQDkQGhf0eDYbccl7Nj6TcPnQKmt6laKwFOr5yG0\n\
G6q2QCNmMRbfAqxRF2TSVhIVFzAW9Tc+QuZrqYqsTQdvUlgK\n\
-----END CERTIFICATE-----\n\
";

pub const RENEWED_KEY: &str = "\
-----BEGIN PRIVATE KEY-----\n\
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg1W3v2nEErBEfh0dq\n\
60O08kO1pxWeXawYA0klhcVypRmhRANCAAQuQtFV8fG+ZdARdnqfq7w0EkvpYR18\n\
07ucsssifZeAPUNmVXWbC2I/2DrrBbaJ7JtmIJE7N0oGvKYBiDWqar+b\n\
-----END PRIVATE KEY-----\n\
";

pub const OTHER_CERT: &str = "\
-----BEGIN CERTIFICATE-----\n\
MIIBcDCCASKgAwIBAgIINAECAwQFBgcwBQYDK2VwMBQxEjAQBgNVBAMMCWxvY2Fs\n\
aG9zdDAeFw0yNjAxMDEwMDAwMDBaFw00NjAxMDEwMDAwMDBaMBQxEjAQBgNVBAMM\n\
CWxvY2FsaG9zdDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABLpBEVebP/ppIdgM\n\
ZDxYSJ5jvmOSypdoA7y8PgLSPSho78qWgkZOWl34aMxpAPt6bTzHSWhmHazg0yaU\n\
mNw+u36jYzBhMBQGA1UdEQQNMAuCCWxvY2FsaG9zdDAJBgNVHRMEAjAAMB0GA1Ud\n\
DgQWBBSc4+k5JIPlrefTCLHc5KV1sXZbyTAfBgNVHSMEGDAWgBRr5/uK/P8Sgteo\n\
DkTAPouh367VMTAFBgMrZXADQQANmIpYd3HHipYHIW+IL9ydDQq4D+lNrn9b3O82\n\
qsVveGt/I774IPsZIV5srHuB2PRTDqwN2aPtszU2ObIFkmEI\n\
-----END CERTIFICATE-----\n\
-----BEGIN CERTIFICATE-----\n\
MIIBQDCB86ADAgECAggzAQIDBAUGBzAFBgMrZXAwFDESMBAGA1UEAwwJbG9jYWxo\n\
b3N0MB4XDTI2MDEwMTAwMDAwMFoXDTQ2MDEwMTAwMDAwMFowFDESMBAGA1UEAwwJ\n\
bG9jYWxob3N0MCowBQYDK2VwAyEAgS57XBJBa1ugKpJyE0iXgipLthqdaI3Eh4KA\n\
6Q/Om6ujYzBhMB0GA1UdDgQWBBRr5/uK/P8SgteoDkTAPouh367VMTAfBgNVHSME\n\
GDAWgBRr5/uK/P8SgteoDkTAPouh367VMTAPBgNVHRMBAf8EBTADAQH/MA4GA1Ud\n\
DwEB/wQEAwIChDAFBgMrZXADQQAGWz2/n6j2xbw2jxtE7TNzaV6iZCJHBoVITjV4\n\
hMSKafRt4afhpl+5M7E8LYFLEI9TOpGTQZayeB3UJqyNbSAE\n\
-----END CERTIFICATE-----\n\
";

pub const OTHER_KEY: &str = "\
-----BEGIN PRIVATE KEY-----\n\
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgF+qhveZa214ExSl2\n\
2hjqmNG5imfjwGNy+0eG++qslvShRANCAAS6QRFXmz/6aSHYDGQ8WEieY75jksqX\n\
aAO8vD4C0j0oaO/KloJGTlpd+GjMaQD7em08x0loZh2s4NMmlJjcPrt+\n\
-----END PRIVATE KEY-----\n\
";
