#!/usr/bin/env bash
# Build the release binary of a product and install/refresh it under
# ~/.local/share/<binary>.
#
#   scripts/update.sh [product]   # space (default), notes, pass or chat;  make update [product]
#
# The menu entry (<productName>.desktop) launches the *installed* copy, so a
# running app keeps working while we build and is picked up on next launch.
set -e

# The root of the repository: this file is in scripts/.
ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

# The product: its crate, binary, names (docs/platform-spec.md 13.2).
source "$ROOT_DIR/scripts/product.sh"
product_env "${1:-space}"

# One-time data/dev-prefix setup + build env vars + project-local toolchain.
source "$ROOT_DIR/scripts/build-env.sh"

APP_ID="$PRODUCT_BIN"
INSTALL_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/$APP_ID"
APPS_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/applications"
ICONS_BASE="${XDG_DATA_HOME:-$HOME/.local/share}/icons/hicolor"

echo ">> Building $PRODUCT_NAME $PRODUCT_VERSION (release)..."
# The CLI of the UI project, from the root; TAURI_APP_PATH names the product.
tauri_cli_ready
cd "$ROOT_DIR"
"$TAURI_CLI" build --no-bundle

echo ">> Installing into $INSTALL_DIR ..."
mkdir -p "$INSTALL_DIR"
install -m 755 "$ROOT_DIR/data/target/release/$APP_ID" "$INSTALL_DIR/$APP_ID"

# Launcher: the binary links against the project-local WebKit in data/dev-prefix/
# and needs the webkit-run.sh bwrap overlay for WebKit's helper processes, so
# the install stays tied to this checkout.
cat > "$INSTALL_DIR/run.sh" << EOF
#!/usr/bin/env bash
# Generated by update.sh — launches the installed release build.
export LD_LIBRARY_PATH="$ROOT_DIR/data/dev-prefix/usr/lib/x86_64-linux-gnu:\$LD_LIBRARY_PATH"
export WEBKIT_DISABLE_SANDBOX=1
exec "$ROOT_DIR/scripts/webkit-run.sh" "$INSTALL_DIR/$APP_ID" "\$@"
EOF
chmod 755 "$INSTALL_DIR/run.sh"

# Icons (same set dev.sh installs — idempotent)
icon_src="$APP_DIR/icons"
for entry in "32x32:32x32.png" "64x64:64x64.png" "128x128:128x128.png" \
             "256x256:128x128@2x.png" "512x512:icon.png"; do
  size="${entry%%:*}"; file="$icon_src/${entry#*:}"
  [ -f "$file" ] || continue
  mkdir -p "$ICONS_BASE/$size/apps"
  cp -f "$file" "$ICONS_BASE/$size/apps/$APP_ID.png"
done

# Menu entry. The deb package ships /usr/share/applications/<productName>.desktop
# pointing at the (root-owned, non-updatable) /usr/bin binary; per the XDG spec a
# user-local file with the SAME desktop-file ID shadows it, so the menu entry
# of the product launches our freshly installed build instead.
mkdir -p "$APPS_DIR"
cat > "$APPS_DIR/$PRODUCT_NAME.desktop" << EOF
[Desktop Entry]
Type=Application
Name=$PRODUCT_NAME
Comment=$(product_desktop_field Comment)
Exec=$INSTALL_DIR/run.sh %U
Icon=$APP_ID
Terminal=false
Categories=$(product_desktop_field Categories)
StartupNotify=true
StartupWMClass=$APP_ID
X-Veydan-Release=true
EOF

# Drop the visible entry an older update.sh wrote under a different file name —
# it would show up as a duplicate next to the shadowed deb entry. (dev.sh's
# hidden icon-matching entry uses the same name; it recreates itself on the
# next dev run.)
if grep -qs '^X-Veydan-Release=true' "$APPS_DIR/$APP_ID.desktop"; then
  rm -f "$APPS_DIR/$APP_ID.desktop"
fi

command -v update-desktop-database >/dev/null 2>&1 && \
  update-desktop-database "$APPS_DIR" >/dev/null 2>&1 || true
command -v gtk-update-icon-cache >/dev/null 2>&1 && \
  gtk-update-icon-cache -q -t -f "$ICONS_BASE" >/dev/null 2>&1 || true

echo ""
echo ">> Done! Installed: $INSTALL_DIR/$APP_ID ($PRODUCT_VERSION)"
echo ">> Restart the app from the menu to use the updated version."
